trigger: none

pool:
  vmImage: ubuntu-latest
variables: 
- group : Main


steps:
- script: |
    echo Variables in Variable Group
    echo $(TestVariable1)
    echo $(TestVariable2)
    echo $(TestVariable4)
    echo $(TestVariable3)
    echo $(WorkItemId)
  displayName: 'Echo Variables'
